<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Demo_date</name>
   <tag></tag>
   <elementGuidId>c342748e-df94-4236-95a7-67ccb73753fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ea55970-61a4-4560-9b3a-abdf2f96b3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b63a5167-1227-4209-bcff-3e195981e6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control docs-date</value>
      <webElementGuid>642f85ce-6d1a-4390-a222-dfdd17f1eb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>288f6a78-4703-42bb-a5e4-ec2a63b1fba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>c109b14b-949d-4ce1-9467-ca4a82ceabca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1c864baa-9ae9-4086-a592-870e0d03e850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-3&quot;]/div[@class=&quot;docs-datepicker&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control docs-date&quot;]</value>
      <webElementGuid>a7c69bb1-72fc-4c4a-b604-ccb57e5a2d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='date']</value>
      <webElementGuid>7595f4ab-9533-49d0-b577-ca6e133850e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8877f445-880f-4a4d-b07b-0a4d37324ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date' and @placeholder = 'Pick a date']</value>
      <webElementGuid>c32a4fca-62e8-4c4d-a415-2b5ef2809e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
